### ISSUE TITLE
Add separate plot for Saldo końcowe

### ISSUE THREAD

**Issue by Plinsboorg** [HackerspaceKRK/raport-next#1]
Feature request.
add additional bar plot to display "Saldo końcowe". "bezpiecznaja granica"can be displayed as a line there.

**Comment by wprzyb** [comment]
Soon-ish, i have to get rid of legacy mess with the fact, that "summary" and "plot" data are seoarate, yet they do the same purpose, then i need to fiddle with a functions, that prepare data for charts.

**Comment by wprzyb** [comment]
I guess i found the way ;DD

**Comment by wprzyb** [comment]
![image](https://github.com/HackerspaceKRK/raport-next/assets/1530495/97ee03c3-0cec-4f01-aa0c-a76ff458159f)
